name: CD Catculator Web

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true

    name: Deploy Service
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [18.12.1]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Make service envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_API_SERVER_ENDPOINT: ${{ secrets.REACT_APP_API_SERVER_ENDPOINT }}
          file_name: .env

      - name: Build application
        run: yarn build

        # AWS credential 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRETS }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Deploy application to S3
      - name: Deploy to S3
        run: aws s3 sync build/ s3://${{ secrets.AWS_S3_DEPLOY_BUCKET }} --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CDN_DISTRIBUTION_ID }} --paths "/*"
